---
apiVersion: v1
kind: Namespace
metadata:
  name: nbot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: nbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
      tier: console
      track: stable
  template:
    metadata:
      labels:
        app: console
        tier: console
        track: stable
    spec:
      containers:
      - name: console
        image: localhost:32000/console:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: console-service
  namespace: nbot
spec:
  type: ClusterIP
  selector:
    app: console
    tier: console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-ingress
  namespace: nbot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: public
spec:
  ingressClassName: public
  tls:
  - hosts:
    - nbotui.web.ksemin.in
    secretName: console-web-ksemin-in-tls
  rules:
    - host: nbotui.web.ksemin.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console-service
                port:
                  number: 80
